version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api 
    restart: always
    ports:
      - "${PORT}:3000"
    depends_on:
      - mongo
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: ${MONGO_URI}
    healthcheck:
      test: ["CMD", "curl", ":${PORT}"]
      interval: 5s
      timeout: 3s
      retries: 6

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  mongo:
    image: mongo:6.0.1
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  redis_data:
  mongo_data: