version: "3.8"

services:
  api_1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - meilisearch
    env_file:
      - .env

  meilisearch:
    image: getmeili/meilisearch
    user: root
    volumes:
      - meili_data:/meili_data/
    environment:
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_API_KEY}
      MEILI_NO_ANALYTICS: true

volumes:
  redis_data:
  meili_data:
